### ISSUE TITLE
Fix travis build

### ISSUE THREAD

**Issue by bitbeans** [bitbeans/minisign-net#4]
I can not see the problem: `System.DllNotFoundException : libsodium`

Travis: https://travis-ci.org/bitbeans/minisign-net

@adamcaudill @fraga can you take a look?

On my local systems i do not have any problems.

**Comment by bitbeans** [comment]
ok old build style just works fine ...

**Comment by fraga** [comment]
Sorry @bitbeans was on vacation glad you fixed it :)

**Comment by bitbeans** [comment]
I hope you have recovered well :)
